---
services:
  devcontainer:
    container_name: devcontainer-ai-coder
    image: dceoy/devcontainer-ai-coder:latest
    build:
      context: .
      dockerfile: Dockerfile
      target: cli
      platforms:
        - linux/arm64
        - linux/amd64
      args:
        UBUNTU_VERSION: '24.04'
        PYTHON_VERSION: '3.13'
        USER_NAME: cli
        USER_UID: 1001
        USER_GID: 1001
      cache_from:
        - type=gha
      cache_to:
        - type=gha,mode=max
    volumes:
      - ${PWD}:/workspace
      - ${HOME}/.aws:/home/cli/.aws
      - ${HOME}/.gitconfig:/home/cli/.gitconfig
    working_dir: /workspace
    entrypoint:
      - /usr/bin/zsh
    command:
      - -c
      - sleep infinity
