---
services:
  cli-devcontainer:
    container_name: cli-devcontainer
    image: dceoy/cli:devcontainer
    build:
      context: .
      dockerfile: Dockerfile
      target: cli
      platforms:
        - linux/arm64
        - linux/amd64
      args:
        UBUNTU_VERSION: '24.04'
        PYTHON_VERSION: '3.13'
        USER_NAME: cli
        USER_UID: 1001
        USER_GID: 1001
      cache_from:
        - type=gha
      cache_to:
        - type=gha,mode=max
    volumes:
      - .:/mnt/host
    working_dir: /mnt/host
    entrypoint:
      - /usr/bin/zsh
      - -l
    command:
      - sleep
      - infinity
